### ISSUE TITLE
Execution failed for task 'jar2npm'

### ISSUE THREAD

**Issue by SumeetGohil** [svok/kotlin-jar2npm-plugin#2]
Hey Any idea what will be the cause ?

* What went wrong:
Execution failed for task ':webapp:jar2npm'.
> java.nio.file.FileAlreadyExistsException: 

Trace produced: 

```
 at com.crowdproj.plugins.jar2npm.KotlinJar2NpmTaskKt.ensureSymlink(KotlinJar2NpmTask.kt:127)
        at com.crowdproj.plugins.jar2npm.KotlinJar2NpmTaskKt.access$ensureSymlink(KotlinJar2NpmTask.kt:1)
        at com.crowdproj.plugins.jar2npm.KotlinJar2NpmTask.jar2npm(KotlinJar2NpmTask.kt:113)

```

Thank you in advance.

**Comment by svok** [comment]
Hey.
OK, lets reason.
The plugin first extracts the contents of kotlinjs jar-s to node_modules_imported. Then it  installs npm, yarn and all from package.json. On the last step it makes symlinks from packages in node_modules_imported to node_modules. 

I suppose the following reasons for the failure.
1. You use Windows. I never tested this plugin with that OS and have no idea how it behaves.
2. You have files in your node_modules with the same names as those in node_modules_imported but they are not symlinks. This can happen when you import the same package both in npm and jar. Please, explore this case if it relates to you. This looks as a bug and requires special handling. The solutions may be: (1) deny creating symlinks; (2) enforce creating symlink first removing the file/directory from node_modules; (3) make some plugin settings.
Before I fix the issue I'd like to get more information on that: what is the conflicting module and what is best to do with it.

**Comment by SumeetGohil** [comment]
Thank you for reverting back in this sort period of time.

Currently i am using -> `find . -type l -exec test ! -e {} \; -delete` command to clear our symlink and `jar2npm` works perfect.


Give me sometime i'll try to share more details for you.
